deploy-docker:
  only:
    - main
  tags:
    - lasagna
  script:
    - cd /home/adadev/docker_folder/sofware_solution/digitec.lasagna.fira.id
    - git stash
    - git pull origin main
    - git stash pop
    - docker-compose -f docker.stag.yaml up --force-recreate -d --build
